// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caiphwhxwvbwaseiczqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaXBod2h4d3Zid2FzZWljenFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MTY0NzMsImV4cCI6MjA4NTI5MjQ3M30.m6UBSdjESeOaqVEoP4BXkK8UHWOXyZPOQ2aKGhdVo-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});